---

- name: Create Jeager Ingress Resource
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ role_path }}/templates/ingress/ingress.yaml.j2') | from_yaml_all }}"
    state: present
    namespace: jaeger