---

- name: Configure Jaeger All-In-One Instance
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ role_path }}/templates/instance/jaeger.yaml.j2') | from_yaml_all }}"
    state: present
    namespace: jaeger
