---
# ####################################################################
#                             Install ArgoCD
# ####################################################################

- name: ArgoCD
  include_tasks: 
    file: install.yml
    apply:
      tags: install
  tags:
    - install

# ####################################################################
#                             ArgoCD Ingress
# ####################################################################

- name: ArgoCD Ingress
  include_tasks: 
    file: ingress.yml
    apply:
      tags: ingress
  tags: ingress
