---
# ####################################################################
#                             Install Grafana
# ####################################################################

- name: Grafana
  include_tasks: 
    file: install.yml
    apply:
      tags: install
  tags:
    - install

# ####################################################################
#                             Grafana Ingress
# ####################################################################

- name: Grafana Ingress
  include_tasks: 
    file: ingress.yml
    apply:
      tags: ingress
  tags: ingress
