---

- name: Create OTel Collecor namespace 
  kubernetes.core.k8s:
    name: otel-collector
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy OTel Collector
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ role_path }}/templates/otel-collector.yaml.j2') | from_yaml_all }}"
    state: present