---

- name: Copy cluster config template
  template:
    src: "{{ role_path }}/templates/cluster-config.yaml.j2"
    dest: "/tmp/cluster-config.yaml"
    mode: 0644

- name: Create kind cluster
  shell: "kind create cluster --name {{ cluster_name }} --config /tmp/cluster-config.yaml"

- name: Cluster creation has been finished
  debug:
    msg: "Cluster creation of kind cluster {{ cluster_name }} has been finished."

- name: Get Cluster Kubeconfig
  shell: "kind get kubeconfig --name {{ cluster_name }}"
  register: kubeconfig

- name: Copy Kubeconfig in /tmp
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: /tmp/kubeconfig.yml