---
# ####################################################################
#                             Docker
# ####################################################################

- name: Docker
  include_tasks: 
    file: docker.yml
    apply:
      tags: install
  tags:
    - install

# ####################################################################
#                             Install kind
# ####################################################################

- name: Kind
  include_tasks: 
    file: kind.yml
    apply:
      tags: install
  tags: install

# ####################################################################
#                             Create cluster
# ####################################################################

- name: Create cluster {{ cluster_name }}
  include_tasks: 
    file: create.yml
    apply:
      tags: create
  tags:
    - create

# ####################################################################
#                             Create Nginx Ingress
# ####################################################################

- name: Create Nginx Ingress resource
  include_tasks: 
    file: ingress.yml
    apply:
      tags: ingress
  tags:
    - ingress

# ####################################################################
#                             Delete cluster
# ####################################################################

- name: Delete cluster {{ cluster_name }}
  include_tasks: 
    file: delete.yml
    apply:
      tags: delete
  tags:
    - delete
